//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('blogs')
export class blogsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Photos: string;

  @Column('text', { nullable: true })
  Title: string;

  @Column('date', { nullable: true })
  DateTime: Date;

  @Column('integer', { nullable: true })
  Author: number;

  @Column('text', { nullable: true })
  Content: string;

  @Column('integer', { nullable: true })
  OtherBlogs: number;
}
