//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('emergencyContacts')
export class emergencyContactsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  TrustedContactList: number;

  @Column('text', { nullable: true })
  GuidePhoneNumber: string;

  @Column('text', { nullable: true })
  NearestHospitalNumber: string;

  @Column('text', { nullable: true })
  NearestPoliceStationNumber: string;
}
