//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('trips')
export class tripsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  ListOfTrips: string;

  @Column('real', { nullable: true })
  DistanceTravelled: number;

  @Column('integer', { nullable: true })
  LocationsPinpointed: number;
}
