//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('users')
export class usersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  Username: string;

  @Column('text', { nullable: true })
  Mail: string;

  @Column('text', { nullable: true })
  Password: string;

  @Column('text', { nullable: true })
  TravelType: string;

  @Column('text', { nullable: true })
  TravelPreferences: string;
}
