//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const blogsTitle = () => {
  const record = useRecordContext();
  return <span>blogs {record ? `"${record.Title}"` : ''}</span>;
};

export const blogsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ImageField source="Photos" />
      <TextField source="Title" />
      <DateField source="DateTime" />
      <ReferenceField source="Author" reference="users" />
      <TextField source="Content" />
      <ReferenceField source="OtherBlogs" reference="blogs" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const blogsEdit = () => (
  <Edit title={<blogsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ImageInput source="Photos" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Title" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="DateTime" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="Author" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Content" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="OtherBlogs" reference="blogs" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const blogsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ImageInput source="Photos" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Title" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="DateTime" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="Author" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="Content" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="OtherBlogs" reference="blogs" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  <ReferenceInput source="Author" label="Author" reference="users" alwaysOn />,
  ,
  <ReferenceInput
    source="OtherBlogs"
    label="OtherBlogs"
    reference="blogs"
    alwaysOn
  />,
];
