//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Journal" />
    <CardContent>
      This app is basically a travel community that connects the users based on
      their preferences and nearby locations. It also has a travel bot that
      gives users every update regarding their trips like the accesories
      requires on that day and also suggests blogs depending on the location
      they are in.It also has an emergency button in case of emergency where it
      informs to nearest hospital and police station .
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
