//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    users: {
      name: 'Users',
      fields: {
        Username: 'Username',
        Mail: 'Mail',
        Password: 'Password',
        TravelType: 'Travel Type',
        TravelPreferences: 'Travel Preferences',
        id: 'id',
      },
    },
    locations: {
      name: 'Locations',
      fields: { Latitude: 'Latitude', Longitude: 'Longitude', id: 'id' },
    },
    trips: {
      name: 'Trips',
      fields: {
        ListOfTrips: 'List Of Trips',
        DistanceTravelled: 'Distance Travelled',
        LocationsPinpointed: 'Locations Pinpointed',
        id: 'id',
      },
    },
    accessories: {
      name: 'Accessories',
      fields: {
        NecessaryItems: 'Necessary Items',
        WeatherDetails: 'Weather Details',
        id: 'id',
      },
    },
    blogs: {
      name: 'Blogs',
      fields: {
        Photos: 'Photos',
        Title: 'Title',
        DateTime: 'Date Time',
        Author: 'Author',
        Content: 'Content',
        OtherBlogs: 'Other Blogs',
        id: 'id',
      },
    },
    emergencyContacts: {
      name: 'Emergency Contacts',
      fields: {
        TrustedContactList: 'Trusted Contact List',
        GuidePhoneNumber: 'Guide Phone Number',
        NearestHospitalNumber: 'Nearest Hospital Number',
        NearestPoliceStationNumber: 'Nearest Police Station Number',
        id: 'id',
      },
    },
    journal: { name: 'Journal', fields: { Blogs: 'Blogs', id: 'id' } },
  },
};
const frResources = {
  resources: {
    users: {
      name: 'Users (fr)',
      fields: {
        Username: 'Username (fr)',
        Mail: 'Mail (fr)',
        Password: 'Password (fr)',
        TravelType: 'Travel Type (fr)',
        TravelPreferences: 'Travel Preferences (fr)',
        id: 'id',
      },
    },
    locations: {
      name: 'Locations (fr)',
      fields: {
        Latitude: 'Latitude (fr)',
        Longitude: 'Longitude (fr)',
        id: 'id',
      },
    },
    trips: {
      name: 'Trips (fr)',
      fields: {
        ListOfTrips: 'List Of Trips (fr)',
        DistanceTravelled: 'Distance Travelled (fr)',
        LocationsPinpointed: 'Locations Pinpointed (fr)',
        id: 'id',
      },
    },
    accessories: {
      name: 'Accessories (fr)',
      fields: {
        NecessaryItems: 'Necessary Items (fr)',
        WeatherDetails: 'Weather Details (fr)',
        id: 'id',
      },
    },
    blogs: {
      name: 'Blogs (fr)',
      fields: {
        Photos: 'Photos (fr)',
        Title: 'Title (fr)',
        DateTime: 'Date Time (fr)',
        Author: 'Author (fr)',
        Content: 'Content (fr)',
        OtherBlogs: 'Other Blogs (fr)',
        id: 'id',
      },
    },
    emergencyContacts: {
      name: 'Emergency Contacts (fr)',
      fields: {
        TrustedContactList: 'Trusted Contact List (fr)',
        GuidePhoneNumber: 'Guide Phone Number (fr)',
        NearestHospitalNumber: 'Nearest Hospital Number (fr)',
        NearestPoliceStationNumber: 'Nearest Police Station Number (fr)',
        id: 'id',
      },
    },
    journal: {
      name: 'Journal (fr)',
      fields: { Blogs: 'Blogs (fr)', id: 'id' },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
